test1:
	@echo "=== Test 1: ex1.var + ex1.con (none) ==="
	python main.py ex1.var ex1.con none
	@echo "=== Test 1: ex1.var + ex1.con (fc) ==="
	python main.py ex1.var ex1.con fc

test2:
	@echo "=== Test 2: ex2.var + ex2.con (none) ==="
	python main.py ex2.var ex2.con none
	@echo "=== Test 2: ex2.var + ex2.con (fc) ==="
	python main.py ex2.var ex2.con fc
